Repository EGA-archive/FEGA-onboarding, pull requests merged in 2022-08, with the labels that each got.

#18 Added pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/request_change.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#29 Short review of contents
  .github/pull_request_template.md
  CONTRIBUTORS.yaml
  README.md
  docs/index.md
  docs/topics/data-metadata-management/index.md
  docs/topics/governance-legal/index.md
  docs/topics/maturity-model/index.md
  docs/topics/outreach-training/index.md
  docs/topics/technical-operational/index.md
Labels: bug, documentation

#30 Add requirements for Use Case presentation at the ELIXIR FHD community call
  docs/index.md
  docs/topics/governance-legal/index.md
Labels: documentation

#32 External links open in new tabs
  docs/index.md
  docs/topics/data-metadata-management/index.md
  docs/topics/governance-legal/index.md
  docs/topics/maturity-model/index.md
  docs/topics/outreach-training/index.md
  docs/topics/technical-operational/index.md
Labels: feature

#33 Added suggestion for what to review to PR template
  .github/pull_request_template.md
Labels: documentation

#34 Added YAML templates of bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/request_change.md
  .github/ISSUE_TEMPLATE/request_change.yaml
Labels: documentation

#35 Quick fix issue templates - Added emojis
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/request_change.yaml
Labels: bug
