Repository EGA-archive/FEGA-onboarding, pull requests merged in 2023-05, with the labels that each got.

#45 BioHackathon 2022 technical content addition
  CONTRIBUTORS.yaml
  docs/search.html
  docs/search_data.json
  docs/topics/technical-operational/countries_tech_stack/component_description.html
  docs/topics/technical-operational/countries_tech_stack/finland_tech_stack.html
  docs/topics/technical-operational/countries_tech_stack/germany_tech_stack.html
  docs/topics/technical-operational/countries_tech_stack/national_nodes_technical_stack.html
  docs/topics/technical-operational/countries_tech_stack/norway_tech_stack.html
  docs/topics/technical-operational/countries_tech_stack/spain_tech_stack.html
  docs/topics/technical-operational/countries_tech_stack/sweden_tech_stack.html
  docs/topics/technical-operational/index.md
Labels: documentation, feature, FEGA-thon

#49 Change metadata link
  docs/topics/data-metadata-management/index.md
Labels: FEGA-thon

#44 Updated link to version 2 of the FEGA end-2-end demo doc
  docs/topics/technical-operational/index.md
Labels: FEGA-thon

#43 Add link to MM evaluation in Technical and Operational section
  CONTRIBUTORS.yaml
  docs/topics/technical-operational/index.md
Labels: FEGA-thon

#48 Add missing GitHub and homepages links
  docs/topics/data-metadata-management/index.md
Labels: FEGA-thon

#46 Update CONTRIBUTORS.yaml
  CONTRIBUTORS.yaml
Labels: FEGA-thon

#47 Add second link to FEGA Node Operations Guidelines. Fixes #37
  docs/topics/governance-legal/index.md
Labels: FEGA-thon

#53 Update Outreach and Establishing node pages
  CONTRIBUTORS.yaml
  docs/index.md
  docs/topics/outreach-training/index.md
Labels: FEGA-thon

#56 Update index.md
  docs/topics/technical-operational/index.md
Labels: FEGA-thon

#57 Harmonisation of terms
  CONTRIBUTORS.yaml
  docs/index.md
Labels: FEGA-thon

#62 Update CONTRIBUTORS.yaml
  CONTRIBUTORS.yaml
Labels: FEGA-thon

#59 Add content about the benefits/value of joining FEGA
  docs/index.md
Labels: documentation, FEGA-thon

#63 Portugal: Technical info
  CONTRIBUTORS.yaml
  docs/topics/technical-operational/countries_tech_stack/national_nodes_technical_stack.html
  docs/topics/technical-operational/countries_tech_stack/portugal_tech_stack.html
Labels: documentation
